# Generated by Django 6.0.4 on 2026-04-24 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('closed', 'Fermé'), ('pending', 'En attente')], default='open', max_length=10)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('unread_by_admin', models.PositiveSmallIntegerField(default=0)),
                ('unread_by_traveler', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, help_text='Optional — links conversation to a specific property', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='properties.property')),
                ('traveler', models.ForeignKey(limit_choices_to={'role__in': ['traveler', 'owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('traveler', 'Voyageur'), ('admin', 'Administrateur')], max_length=10)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('booking_confirmed', 'Réservation confirmée'), ('booking_cancelled', 'Réservation annulée'), ('new_message', 'Nouveau message'), ('review_posted', 'Nouvel avis'), ('listing_approved', 'Établissement approuvé'), ('listing_rejected', 'Établissement rejeté')], max_length=25)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='URL to redirect on click', max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
