# Generated by Django 6.0.4 on 2026-05-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_fix_sender_type_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
